.TH "OPENSHIFT" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift start \- Launch OpenShift components


.SH SYNOPSIS
.PP
\fBopenshift start\fP [OPTIONS]


.SH DESCRIPTION
.PP
Start components of OpenShift

.PP
This command launches components of OpenShift.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file containing Azure container registry configuration information.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH SEE ALSO
.PP
\fBopenshift(1)\fP, \fBopenshift\-start\-etcd(1)\fP, \fBopenshift\-start\-master(1)\fP, \fBopenshift\-start\-network(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
